travis:
  secure:
    BINSTAR_TOKEN: JlAR3s6i5V4DSnIY/uF7IcxqX50vMjcybi2kGMwr00cjrmXzJDxDFPgd35FgpD2QWUBB0rD4I+dt/svyqhnlR5b20DnRucdQPeb/Mv6lPMY2hBA0Q1UhM5V7f7R0cl2OpPx1sYXtitarSrQBXGTNlopham6ZW+9+SMO13YRmnUY/yzLbU89Ac50j6OtSB9m5EM3OYvKjvtm5IEs+bgveCzuDZXA/PjZ/D+o7r7iBQGp2MpPo8ssW2FBZ01hIoSKwqWKg3fo8RWhP4uY2qxp9T9qTyQZtuki4ghQnghOkcG8Snswg2gx7dWUtLhLG5tI34rRdqy/tYoiWrhNXWCYZFUupXW3jb2zQDfM+MdheAL7S5lhlofIzClc5m7mvZedwDmrz+xTxG0cpBDhIeoVdUrpr4yTxth85JYnHWx9ZIii9EXaTouWljlfWyDFKYANFj6UlJL41n+qN/97zoW2uLKAnHCczhA/CxrHfsyAWqNiblQgB/hTPa4Ds94v6h+vITZncpospIVqbVUg5OJkt8V0MdltfjGautQNAFJvhd9wGFZDlmM5Klbwp2TMwcHsQnyvyGFFySFkqpKiCH1vdfSlmWd92HEneTFIgfdKssRQGaQAmWQM2dcWe6dqd9YncyEjG/LqbAoA2tcYz7ckMTRxW1X3cZcAOEMdXeCTqFT4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
